// automatically generated by the FlatBuffers compiler, do not modify

import { WebRtcTransportDump, WebRtcTransportDumpT } from '../../fbs/transport/web-rtc-transport-dump';


export enum SpecificTransportDumpData {
  NONE = 0,
  WebRtcTransportDump = 1
}

export function unionToSpecificTransportDumpData(
  type: SpecificTransportDumpData,
  accessor: (obj:WebRtcTransportDump) => WebRtcTransportDump|null
): WebRtcTransportDump|null {
  switch(SpecificTransportDumpData[type]) {
    case 'NONE': return null; 
    case 'WebRtcTransportDump': return accessor(new WebRtcTransportDump())! as WebRtcTransportDump;
    default: return null;
  }
}

export function unionListToSpecificTransportDumpData(
  type: SpecificTransportDumpData, 
  accessor: (index: number, obj:WebRtcTransportDump) => WebRtcTransportDump|null, 
  index: number
): WebRtcTransportDump|null {
  switch(SpecificTransportDumpData[type]) {
    case 'NONE': return null; 
    case 'WebRtcTransportDump': return accessor(index, new WebRtcTransportDump())! as WebRtcTransportDump;
    default: return null;
  }
}
