// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Uint16String {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Uint16String {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUint16String(bb:flatbuffers.ByteBuffer, obj?:Uint16String):Uint16String {
  return (obj || new Uint16String()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUint16String(bb:flatbuffers.ByteBuffer, obj?:Uint16String):Uint16String {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Uint16String()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startUint16String(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, key:number) {
  builder.addFieldInt16(0, key, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endUint16String(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // value
  return offset;
}

static createUint16String(builder:flatbuffers.Builder, key:number, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  Uint16String.startUint16String(builder);
  Uint16String.addKey(builder, key);
  Uint16String.addValue(builder, valueOffset);
  return Uint16String.endUint16String(builder);
}

unpack(): Uint16StringT {
  return new Uint16StringT(
    this.key(),
    this.value()
  );
}


unpackTo(_o: Uint16StringT): void {
  _o.key = this.key();
  _o.value = this.value();
}
}

export class Uint16StringT {
constructor(
  public key: number = 0,
  public value: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const value = (this.value !== null ? builder.createString(this.value!) : 0);

  return Uint16String.createUint16String(builder,
    this.key,
    value
  );
}
}
