// automatically generated by the FlatBuffers compiler, do not modify

import { RouterDump, RouterDumpT } from '../../fbs/router/router-dump';
import { ConsumeResponse, ConsumeResponseT } from '../../fbs/transport/consume-response';
import { TransportDump, TransportDumpT } from '../../fbs/transport/transport-dump';
import { WebRtcServerDump, WebRtcServerDumpT } from '../../fbs/web-rtc-server/web-rtc-server-dump';
import { ResourceUsage, ResourceUsageT } from '../../fbs/worker/resource-usage';
import { WorkerDump, WorkerDumpT } from '../../fbs/worker/worker-dump';


export enum Body {
  NONE = 0,
  FBS_Router_RouterDump = 1,
  FBS_Transport_TransportDump = 2,
  FBS_Transport_ConsumeResponse = 3,
  FBS_WebRtcServer_WebRtcServerDump = 4,
  FBS_Worker_WorkerDump = 5,
  FBS_Worker_ResourceUsage = 6
}

export function unionToBody(
  type: Body,
  accessor: (obj:ConsumeResponse|ResourceUsage|RouterDump|TransportDump|WebRtcServerDump|WorkerDump) => ConsumeResponse|ResourceUsage|RouterDump|TransportDump|WebRtcServerDump|WorkerDump|null
): ConsumeResponse|ResourceUsage|RouterDump|TransportDump|WebRtcServerDump|WorkerDump|null {
  switch(Body[type]) {
    case 'NONE': return null; 
    case 'FBS_Router_RouterDump': return accessor(new RouterDump())! as RouterDump;
    case 'FBS_Transport_TransportDump': return accessor(new TransportDump())! as TransportDump;
    case 'FBS_Transport_ConsumeResponse': return accessor(new ConsumeResponse())! as ConsumeResponse;
    case 'FBS_WebRtcServer_WebRtcServerDump': return accessor(new WebRtcServerDump())! as WebRtcServerDump;
    case 'FBS_Worker_WorkerDump': return accessor(new WorkerDump())! as WorkerDump;
    case 'FBS_Worker_ResourceUsage': return accessor(new ResourceUsage())! as ResourceUsage;
    default: return null;
  }
}

export function unionListToBody(
  type: Body, 
  accessor: (index: number, obj:ConsumeResponse|ResourceUsage|RouterDump|TransportDump|WebRtcServerDump|WorkerDump) => ConsumeResponse|ResourceUsage|RouterDump|TransportDump|WebRtcServerDump|WorkerDump|null, 
  index: number
): ConsumeResponse|ResourceUsage|RouterDump|TransportDump|WebRtcServerDump|WorkerDump|null {
  switch(Body[type]) {
    case 'NONE': return null; 
    case 'FBS_Router_RouterDump': return accessor(index, new RouterDump())! as RouterDump;
    case 'FBS_Transport_TransportDump': return accessor(index, new TransportDump())! as TransportDump;
    case 'FBS_Transport_ConsumeResponse': return accessor(index, new ConsumeResponse())! as ConsumeResponse;
    case 'FBS_WebRtcServer_WebRtcServerDump': return accessor(index, new WebRtcServerDump())! as WebRtcServerDump;
    case 'FBS_Worker_WorkerDump': return accessor(index, new WorkerDump())! as WorkerDump;
    case 'FBS_Worker_ResourceUsage': return accessor(index, new ResourceUsage())! as ResourceUsage;
    default: return null;
  }
}
