// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Rtx {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Rtx {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

ssrc():number {
  return this.bb!.readUint32(this.bb_pos);
}

static sizeOf():number {
  return 4;
}

static createRtx(builder:flatbuffers.Builder, ssrc: number):flatbuffers.Offset {
  builder.prep(4, 4);
  builder.writeInt32(ssrc);
  return builder.offset();
}

}
