// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class WebRtcTransportListenServer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WebRtcTransportListenServer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWebRtcTransportListenServer(bb:flatbuffers.ByteBuffer, obj?:WebRtcTransportListenServer):WebRtcTransportListenServer {
  return (obj || new WebRtcTransportListenServer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWebRtcTransportListenServer(bb:flatbuffers.ByteBuffer, obj?:WebRtcTransportListenServer):WebRtcTransportListenServer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WebRtcTransportListenServer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

webRtcServerId():string|null
webRtcServerId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
webRtcServerId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startWebRtcTransportListenServer(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addWebRtcServerId(builder:flatbuffers.Builder, webRtcServerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, webRtcServerIdOffset, 0);
}

static endWebRtcTransportListenServer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // web_rtc_server_id
  return offset;
}

static createWebRtcTransportListenServer(builder:flatbuffers.Builder, webRtcServerIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  WebRtcTransportListenServer.startWebRtcTransportListenServer(builder);
  WebRtcTransportListenServer.addWebRtcServerId(builder, webRtcServerIdOffset);
  return WebRtcTransportListenServer.endWebRtcTransportListenServer(builder);
}

unpack(): WebRtcTransportListenServerT {
  return new WebRtcTransportListenServerT(
    this.webRtcServerId()
  );
}


unpackTo(_o: WebRtcTransportListenServerT): void {
  _o.webRtcServerId = this.webRtcServerId();
}
}

export class WebRtcTransportListenServerT {
constructor(
  public webRtcServerId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const webRtcServerId = (this.webRtcServerId !== null ? builder.createString(this.webRtcServerId!) : 0);

  return WebRtcTransportListenServer.createWebRtcTransportListenServer(builder,
    webRtcServerId
  );
}
}
