// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { SctpStreamParameters, SctpStreamParametersT } from '../../fbs/sctp-parameters/sctp-stream-parameters';


export class DumpResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DumpResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDumpResponse(bb:flatbuffers.ByteBuffer, obj?:DumpResponse):DumpResponse {
  return (obj || new DumpResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDumpResponse(bb:flatbuffers.ByteBuffer, obj?:DumpResponse):DumpResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DumpResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sctpStreamParameters(obj?:SctpStreamParameters):SctpStreamParameters|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new SctpStreamParameters()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

label():string|null
label(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
label(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

protocol():string|null
protocol(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
protocol(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startDumpResponse(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, typeOffset, 0);
}

static addSctpStreamParameters(builder:flatbuffers.Builder, sctpStreamParametersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, sctpStreamParametersOffset, 0);
}

static addLabel(builder:flatbuffers.Builder, labelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, labelOffset, 0);
}

static addProtocol(builder:flatbuffers.Builder, protocolOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, protocolOffset, 0);
}

static endDumpResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  builder.requiredField(offset, 6) // type
  builder.requiredField(offset, 10) // label
  builder.requiredField(offset, 12) // protocol
  return offset;
}


unpack(): DumpResponseT {
  return new DumpResponseT(
    this.id(),
    this.type(),
    (this.sctpStreamParameters() !== null ? this.sctpStreamParameters()!.unpack() : null),
    this.label(),
    this.protocol()
  );
}


unpackTo(_o: DumpResponseT): void {
  _o.id = this.id();
  _o.type = this.type();
  _o.sctpStreamParameters = (this.sctpStreamParameters() !== null ? this.sctpStreamParameters()!.unpack() : null);
  _o.label = this.label();
  _o.protocol = this.protocol();
}
}

export class DumpResponseT {
constructor(
  public id: string|Uint8Array|null = null,
  public type: string|Uint8Array|null = null,
  public sctpStreamParameters: SctpStreamParametersT|null = null,
  public label: string|Uint8Array|null = null,
  public protocol: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const type = (this.type !== null ? builder.createString(this.type!) : 0);
  const sctpStreamParameters = (this.sctpStreamParameters !== null ? this.sctpStreamParameters!.pack(builder) : 0);
  const label = (this.label !== null ? builder.createString(this.label!) : 0);
  const protocol = (this.protocol !== null ? builder.createString(this.protocol!) : 0);

  DumpResponse.startDumpResponse(builder);
  DumpResponse.addId(builder, id);
  DumpResponse.addType(builder, type);
  DumpResponse.addSctpStreamParameters(builder, sctpStreamParameters);
  DumpResponse.addLabel(builder, label);
  DumpResponse.addProtocol(builder, protocol);

  return DumpResponse.endDumpResponse(builder);
}
}
