// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class Integer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Integer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInteger(bb:flatbuffers.ByteBuffer, obj?:Integer):Integer {
  return (obj || new Integer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInteger(bb:flatbuffers.ByteBuffer, obj?:Integer):Integer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Integer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startInteger(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldInt32(0, value, 0);
}

static endInteger(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInteger(builder:flatbuffers.Builder, value:number):flatbuffers.Offset {
  Integer.startInteger(builder);
  Integer.addValue(builder, value);
  return Integer.endInteger(builder);
}

unpack(): IntegerT {
  return new IntegerT(
    this.value()
  );
}


unpackTo(_o: IntegerT): void {
  _o.value = this.value();
}
}

export class IntegerT {
constructor(
  public value: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Integer.createInteger(builder,
    this.value
  );
}
}
