// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Value, unionToValue, unionListToValue } from '../../f-b-s/rtp-parameters/value';


export class Parameters {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Parameters {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsParameters(bb:flatbuffers.ByteBuffer, obj?:Parameters):Parameters {
  return (obj || new Parameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsParameters(bb:flatbuffers.ByteBuffer, obj?:Parameters):Parameters {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Parameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

valueType():Value {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Value.NONE;
}

value<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startParameters(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addValueType(builder:flatbuffers.Builder, valueType:Value) {
  builder.addFieldInt8(1, valueType, Value.NONE);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, valueOffset, 0);
}

static endParameters(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  return offset;
}

static createParameters(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, valueType:Value, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  Parameters.startParameters(builder);
  Parameters.addName(builder, nameOffset);
  Parameters.addValueType(builder, valueType);
  Parameters.addValue(builder, valueOffset);
  return Parameters.endParameters(builder);
}
}
