// automatically generated by the FlatBuffers compiler, do not modify

import { ConsumeRequest, ConsumeRequestT } from '../../f-b-s/transport/consume-request';
import { CreateWebRtcServerRequest, CreateWebRtcServerRequestT } from '../../f-b-s/worker/create-web-rtc-server-request';
import { UpdateableSettings, UpdateableSettingsT } from '../../f-b-s/worker/updateable-settings';


export enum Body{
  NONE = 0,
  FBS_Worker_UpdateableSettings = 1,
  FBS_Worker_CreateWebRtcServerRequest = 2,
  FBS_Transport_ConsumeRequest = 3
}

export function unionToBody(
  type: Body,
  accessor: (obj:ConsumeRequest|CreateWebRtcServerRequest|UpdateableSettings) => ConsumeRequest|CreateWebRtcServerRequest|UpdateableSettings|null
): ConsumeRequest|CreateWebRtcServerRequest|UpdateableSettings|null {
  switch(Body[type]) {
    case 'NONE': return null; 
    case 'FBS_Worker_UpdateableSettings': return accessor(new UpdateableSettings())! as UpdateableSettings;
    case 'FBS_Worker_CreateWebRtcServerRequest': return accessor(new CreateWebRtcServerRequest())! as CreateWebRtcServerRequest;
    case 'FBS_Transport_ConsumeRequest': return accessor(new ConsumeRequest())! as ConsumeRequest;
    default: return null;
  }
}

export function unionListToBody(
  type: Body, 
  accessor: (index: number, obj:ConsumeRequest|CreateWebRtcServerRequest|UpdateableSettings) => ConsumeRequest|CreateWebRtcServerRequest|UpdateableSettings|null, 
  index: number
): ConsumeRequest|CreateWebRtcServerRequest|UpdateableSettings|null {
  switch(Body[type]) {
    case 'NONE': return null; 
    case 'FBS_Worker_UpdateableSettings': return accessor(index, new UpdateableSettings())! as UpdateableSettings;
    case 'FBS_Worker_CreateWebRtcServerRequest': return accessor(index, new CreateWebRtcServerRequest())! as CreateWebRtcServerRequest;
    case 'FBS_Transport_ConsumeRequest': return accessor(index, new ConsumeRequest())! as ConsumeRequest;
    default: return null;
  }
}

