FROM alpine

# Install dependencies.
RUN \
	set -x \
	&& apk add \
		nodejs-current npm python3 py3-pip \
		make gcc g++

# Make CC and CXX point to gcc/g++.
ENV LANG="C.UTF-8"
ENV CC="gcc"
ENV CXX="g++"

WORKDIR /mediasoup

CMD ["ash"]
