"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.MediaKind = void 0;
var MediaKind;
(function (MediaKind) {
    MediaKind[MediaKind["AUDIO"] = 0] = "AUDIO";
    MediaKind[MediaKind["VIDEO"] = 1] = "VIDEO";
})(MediaKind = exports.MediaKind || (exports.MediaKind = {}));
