"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Type = void 0;
var Type;
(function (Type) {
    Type[Type["NONE"] = 0] = "NONE";
    Type[Type["SIMPLE"] = 1] = "SIMPLE";
    Type[Type["SIMULCAST"] = 2] = "SIMULCAST";
    Type[Type["SVC"] = 3] = "SVC";
    Type[Type["PIPE"] = 4] = "PIPE";
})(Type = exports.Type || (exports.Type = {}));
