"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConsumerLayersT = exports.ConsumerLayers = void 0;
var consumer_layers_1 = require("./fbs/consumer/consumer-layers");
Object.defineProperty(exports, "ConsumerLayers", { enumerable: true, get: function () { return consumer_layers_1.ConsumerLayers; } });
Object.defineProperty(exports, "ConsumerLayersT", { enumerable: true, get: function () { return consumer_layers_1.ConsumerLayersT; } });
