"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnableTraceEventRequestT = exports.EnableTraceEventRequest = exports.ConsumerScoreT = exports.ConsumerScore = exports.ConsumerLayersT = exports.ConsumerLayers = void 0;
var consumer_layers_1 = require("./fbs/consumer/consumer-layers");
Object.defineProperty(exports, "ConsumerLayers", { enumerable: true, get: function () { return consumer_layers_1.ConsumerLayers; } });
Object.defineProperty(exports, "ConsumerLayersT", { enumerable: true, get: function () { return consumer_layers_1.ConsumerLayersT; } });
var consumer_score_1 = require("./fbs/consumer/consumer-score");
Object.defineProperty(exports, "ConsumerScore", { enumerable: true, get: function () { return consumer_score_1.ConsumerScore; } });
Object.defineProperty(exports, "ConsumerScoreT", { enumerable: true, get: function () { return consumer_score_1.ConsumerScoreT; } });
var enable_trace_event_request_1 = require("./fbs/consumer/enable-trace-event-request");
Object.defineProperty(exports, "EnableTraceEventRequest", { enumerable: true, get: function () { return enable_trace_event_request_1.EnableTraceEventRequest; } });
Object.defineProperty(exports, "EnableTraceEventRequestT", { enumerable: true, get: function () { return enable_trace_event_request_1.EnableTraceEventRequestT; } });
