"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetBufferedAmountResponseT = exports.GetBufferedAmountResponse = void 0;
var get_buffered_amount_response_1 = require("./fbs/data-consumer/get-buffered-amount-response");
Object.defineProperty(exports, "GetBufferedAmountResponse", { enumerable: true, get: function () { return get_buffered_amount_response_1.GetBufferedAmountResponse; } });
Object.defineProperty(exports, "GetBufferedAmountResponseT", { enumerable: true, get: function () { return get_buffered_amount_response_1.GetBufferedAmountResponseT; } });
