"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.BaseTransportOptionsT = exports.BaseTransportOptions = exports.DirectTransportOptionsT = exports.DirectTransportOptions = void 0;
var direct_transport_options_1 = require("./fbs/direct-transport/direct-transport-options");
Object.defineProperty(exports, "DirectTransportOptions", { enumerable: true, get: function () { return direct_transport_options_1.DirectTransportOptions; } });
Object.defineProperty(exports, "DirectTransportOptionsT", { enumerable: true, get: function () { return direct_transport_options_1.DirectTransportOptionsT; } });
var base_transport_options_1 = require("./fbs/transport/base-transport-options");
Object.defineProperty(exports, "BaseTransportOptions", { enumerable: true, get: function () { return base_transport_options_1.BaseTransportOptions; } });
Object.defineProperty(exports, "BaseTransportOptionsT", { enumerable: true, get: function () { return base_transport_options_1.BaseTransportOptionsT; } });
