"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.RemoveProducerRequestT = exports.RemoveProducerRequest = exports.AddProducerRequestT = exports.AddProducerRequest = void 0;
var add_producer_request_1 = require("./fbs/rtp-observer/add-producer-request");
Object.defineProperty(exports, "AddProducerRequest", { enumerable: true, get: function () { return add_producer_request_1.AddProducerRequest; } });
Object.defineProperty(exports, "AddProducerRequestT", { enumerable: true, get: function () { return add_producer_request_1.AddProducerRequestT; } });
var remove_producer_request_1 = require("./fbs/rtp-observer/remove-producer-request");
Object.defineProperty(exports, "RemoveProducerRequest", { enumerable: true, get: function () { return remove_producer_request_1.RemoveProducerRequest; } });
Object.defineProperty(exports, "RemoveProducerRequestT", { enumerable: true, get: function () { return remove_producer_request_1.RemoveProducerRequestT; } });
