"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransportDumpT = exports.TransportDump = void 0;
const flatbuffers = require("flatbuffers");
const transport_dump_data_1 = require("../../fbs/transport/transport-dump-data");
class TransportDump {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsTransportDump(bb, obj) {
        return (obj || new TransportDump()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsTransportDump(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new TransportDump()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    dataType() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint8(this.bb_pos + offset) : transport_dump_data_1.TransportDumpData.NONE;
    }
    data(obj) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
    }
    static startTransportDump(builder) {
        builder.startObject(2);
    }
    static addDataType(builder, dataType) {
        builder.addFieldInt8(0, dataType, transport_dump_data_1.TransportDumpData.NONE);
    }
    static addData(builder, dataOffset) {
        builder.addFieldOffset(1, dataOffset, 0);
    }
    static endTransportDump(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createTransportDump(builder, dataType, dataOffset) {
        TransportDump.startTransportDump(builder);
        TransportDump.addDataType(builder, dataType);
        TransportDump.addData(builder, dataOffset);
        return TransportDump.endTransportDump(builder);
    }
    unpack() {
        return new TransportDumpT(this.dataType(), (() => {
            let temp = (0, transport_dump_data_1.unionToTransportDumpData)(this.dataType(), this.data.bind(this));
            if (temp === null) {
                return null;
            }
            return temp.unpack();
        })());
    }
    unpackTo(_o) {
        _o.dataType = this.dataType();
        _o.data = (() => {
            let temp = (0, transport_dump_data_1.unionToTransportDumpData)(this.dataType(), this.data.bind(this));
            if (temp === null) {
                return null;
            }
            return temp.unpack();
        })();
    }
}
exports.TransportDump = TransportDump;
class TransportDumpT {
    dataType;
    data;
    constructor(dataType = transport_dump_data_1.TransportDumpData.NONE, data = null) {
        this.dataType = dataType;
        this.data = data;
    }
    pack(builder) {
        const data = builder.createObjectOffset(this.data);
        return TransportDump.createTransportDump(builder, this.dataType, data);
    }
}
exports.TransportDumpT = TransportDumpT;
