"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TupleT = exports.Tuple = void 0;
const flatbuffers = require("flatbuffers");
class Tuple {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsTuple(bb, obj) {
        return (obj || new Tuple()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsTuple(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Tuple()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    localIp(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    localPort() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
    }
    remoteIp(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    remotePort() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
    }
    protocol(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    static startTuple(builder) {
        builder.startObject(5);
    }
    static addLocalIp(builder, localIpOffset) {
        builder.addFieldOffset(0, localIpOffset, 0);
    }
    static addLocalPort(builder, localPort) {
        builder.addFieldInt16(1, localPort, 0);
    }
    static addRemoteIp(builder, remoteIpOffset) {
        builder.addFieldOffset(2, remoteIpOffset, 0);
    }
    static addRemotePort(builder, remotePort) {
        builder.addFieldInt16(3, remotePort, 0);
    }
    static addProtocol(builder, protocolOffset) {
        builder.addFieldOffset(4, protocolOffset, 0);
    }
    static endTuple(builder) {
        const offset = builder.endObject();
        builder.requiredField(offset, 4); // local_ip
        builder.requiredField(offset, 8); // remote_ip
        builder.requiredField(offset, 12); // protocol
        return offset;
    }
    static createTuple(builder, localIpOffset, localPort, remoteIpOffset, remotePort, protocolOffset) {
        Tuple.startTuple(builder);
        Tuple.addLocalIp(builder, localIpOffset);
        Tuple.addLocalPort(builder, localPort);
        Tuple.addRemoteIp(builder, remoteIpOffset);
        Tuple.addRemotePort(builder, remotePort);
        Tuple.addProtocol(builder, protocolOffset);
        return Tuple.endTuple(builder);
    }
    unpack() {
        return new TupleT(this.localIp(), this.localPort(), this.remoteIp(), this.remotePort(), this.protocol());
    }
    unpackTo(_o) {
        _o.localIp = this.localIp();
        _o.localPort = this.localPort();
        _o.remoteIp = this.remoteIp();
        _o.remotePort = this.remotePort();
        _o.protocol = this.protocol();
    }
}
exports.Tuple = Tuple;
class TupleT {
    localIp;
    localPort;
    remoteIp;
    remotePort;
    protocol;
    constructor(localIp = null, localPort = 0, remoteIp = null, remotePort = 0, protocol = null) {
        this.localIp = localIp;
        this.localPort = localPort;
        this.remoteIp = remoteIp;
        this.remotePort = remotePort;
        this.protocol = protocol;
    }
    pack(builder) {
        const localIp = (this.localIp !== null ? builder.createString(this.localIp) : 0);
        const remoteIp = (this.remoteIp !== null ? builder.createString(this.remoteIp) : 0);
        const protocol = (this.protocol !== null ? builder.createString(this.protocol) : 0);
        return Tuple.createTuple(builder, localIp, this.localPort, remoteIp, this.remotePort, protocol);
    }
}
exports.TupleT = TupleT;
