name: clang-tidy-review

# It currently only works on pull requests.
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install invoke.
      - name: pip3 install --break-system-packages invoke
        run: pip3 install --break-system-packages invoke

      - name: invoke -r worker mediasoup-worker
        run: invoke -r worker mediasoup-worker

      - uses: ZedThree/clang-tidy-review@v0.22.1
        id: review
        with:
          build_dir: '${{ github.workspace }}/worker/out/Release/build'
          base_dir: '${{ github.workspace }}/worker'
          clang_tidy_version: '21'
          include: 'include/**/*.hpp,src/**/*.cpp'

      # Uploads an artifact containing clang_fixes.json.
      - uses: ZedThree/clang-tidy-review/upload@v0.22.1
        id: upload-review

      # If there are any comments, fail the check.
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
