name: mediasoup-worker

on:
  push:
    branches: [v3]
    paths:
      - 'worker/**'
      - 'worker/scripts/package.json'
      - 'worker/scripts/package-lock.json'
      - '.github/workflows/mediasoup-worker.yaml'
  pull_request:
    paths:
      - 'worker/**'
      - 'worker/scripts/package.json'
      - 'worker/scripts/package-lock.json'
      - '.github/workflows/mediasoup-worker.yaml'
  workflow_dispatch:

concurrency:
  # Cancel a currently running workflow from the same PR, branch or tag when a
  # new workflow is triggered.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      # Here we want to see all errors, not just the first one.
      fail-fast: false
      matrix:
        build:
          - os: ubuntu-22.04
            cc: gcc
            cxx: g++
            build-type: Release
            run-lint: false
            run-test: true
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
          - os: ubuntu-22.04
            cc: clang
            cxx: clang++
            build-type: Release
            run-lint: false
            run-test: true
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
          - os: ubuntu-22.04-arm
            cc: gcc
            cxx: g++
            build-type: Release
            # No clang-format for ARM.
            run-lint: false
            run-test: true
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
          - os: ubuntu-24.04
            cc: gcc
            cxx: g++
            build-type: Release
            pip-break-system-packages: true
            run-lint: false
            run-test: true
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
            # Compile with all Meson option flags enabled once with gcc in
            # Release mode.
            meson_args: '-Dms_log_trace=true -Dms_log_file_line=true -Dms_rtc_logger_rtp=true -Dms_dump_rtp_payload_descriptor=true -Dms_dump_rtp_shared_packet_memory_usage=true -Dms_sctp_stack=true'
          - os: ubuntu-24.04
            cc: gcc
            cxx: g++
            build-type: Debug
            pip-break-system-packages: true
            run-lint: false
            run-test: true
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
            # Compile with all Meson option flags enabled once with gcc in
            # Debug mode.
            meson_args: '-Dms_log_trace=true -Dms_log_file_line=true -Dms_rtc_logger_rtp=true -Dms_dump_rtp_payload_descriptor=true -Dms_dump_rtp_shared_packet_memory_usage=true -Dms_disable_liburing=true -Dms_sctp_stack=true'
          - os: ubuntu-24.04
            cc: clang
            cxx: clang++
            build-type: Release
            pip-break-system-packages: true
            run-lint: false
            run-test: true
            run-test-asan-address: true
            run-test-asan-undefined: true
            run-test-asan-thread: true
            # Let's just compile with all Meson option flags enabled once with
            # clang.
            meson_args: '-Dms_log_trace=true -Dms_log_file_line=true -Dms_rtc_logger_rtp=true -Dms_dump_rtp_payload_descriptor=true -Dms_dump_rtp_shared_packet_memory_usage=true -Dms_sctp_stack=true'
          - os: ubuntu-24.04-arm
            cc: gcc
            cxx: g++
            build-type: Release
            pip-break-system-packages: true
            # No clang-format for ARM.
            run-lint: false
            run-test: true
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
          - os: ubuntu-24.04-arm
            cc: clang
            cxx: clang++
            build-type: Release
            pip-break-system-packages: true
            # No clang-format for ARM.
            run-lint: false
            run-test: true
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
          - os: macos-15
            cc: clang
            cxx: clang++
            build-type: Release
            pip-break-system-packages: true
            # Run lint for the latest macos.
            run-lint: true
            run-test: true
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
          - os: windows-2022
            cc: cl
            cxx: cl
            build-type: Release
            # No clang-format for Windows.
            run-lint: false
            # Maybe some day we fix this.
            run-test: false
            # Address Sanitizer does not work on Windows.
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
          - os: windows-2025
            cc: cl
            cxx: cl
            build-type: Release
            # No clang-format for Windows.
            run-lint: false
            # Maybe some day we fix this.
            run-test: false
            # Address Sanitizer does not work on Windows.
            run-test-asan-address: false
            run-test-asan-undefined: false
            run-test-asan-thread: false
        # A single Node.js version should be fine for C++.
        node:
          - 24

    runs-on: ${{ matrix.build.os }}

    env:
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}
      MEDIASOUP_SKIP_WORKER_PREBUILT_DOWNLOAD: 'true'
      MEDIASOUP_LOCAL_DEV: 'false'
      MEDIASOUP_BUILDTYPE: ${{ matrix.build.build-type }}
      MESON_ARGS: ${{ matrix.build.meson_args }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Configure cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.npm
          key: ${{ matrix.build.os }}-node-${{matrix.build.cc}}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.build.os }}-node-${{matrix.build.cc}}-

      # We need to install pip invoke manually.
      - if: ${{ !matrix.build.pip-break-system-packages }}
        name: pip3 install invoke
        run: pip3 install invoke

      # In modern OSs we need to run pip with this option.
      - if: ${{ matrix.build.pip-break-system-packages }}
        name: pip3 install --break-system-packages invoke
        run: pip3 install --break-system-packages invoke

      # Fail if run-lint is set for non macos.
      - if: ${{ matrix.build.run-lint && !startsWith(matrix.build.os, 'macos') }}
        name: fail if run-lint is set for non macos
        run: |
          echo "run-lint set for non macos"
          exit 1

      # Install clang-format on macos.
      - if: ${{ matrix.build.run-lint && startsWith(matrix.build.os, 'macos') }}
        name: brew install clang-format@22
        run: |
          brew install clang-format@22

      # We need to install npm deps of worker/scripts/package.json.
      - if: ${{ matrix.build.run-lint }}
        name: npm ci --prefix worker/scripts
        run: npm ci --prefix worker/scripts --foreground-scripts

      - if: ${{ matrix.build.run-lint }}
        name: invoke -r worker lint
        run: invoke -r worker lint

      - name: invoke -r worker mediasoup-worker
        run: invoke -r worker mediasoup-worker

      - if: ${{ matrix.build.run-test }}
        name: invoke -r worker test
        run: invoke -r worker test

      # Let's clean everything before rebuilding worker tests with ASAN.
      - if: ${{ matrix.build.run-test-asan-address }}
        name: invoke -r worker test-asan-address
        run: invoke -r worker clean-all && invoke -r worker test-asan-address

      # Let's clean everything before rebuilding worker tests with ASAN.
      - if: ${{ matrix.build.run-test-asan-undefined }}
        name: invoke -r worker test-asan-undefined
        run: invoke -r worker clean-all && invoke -r worker test-asan-undefined

      # Let's clean everything before rebuilding worker tests with ASAN.
      - if: ${{ matrix.build.run-test-asan-thread }}
        name: invoke -r worker test-asan-thread
        run: invoke -r worker clean-all && invoke -r worker test-asan-thread
